
jwt:
  header: Authorization
  secret: my-very-secret-key
  pubkey: pppubkey.pem
  azurejwk : https://login.microsoftonline.com/05d75c05-fa1a-42e7-9cf1-eb416c396f2d/discovery/v2.0/keys
  usijwk: https://logint.maerskline.com/jwt-rest/jwks.json
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8888
spring:
  resources:
    chain:
      enabled: true
management:
  security:
    enabled: true # set to false to disable 'default' Spring Boot security
#endpoints:
#  cors:
#    allowed-origins: '*'
